### ISSUE TITLE
Allow for multiple "named" merges in one directory?

### ISSUE THREAD

**Issue by cottrell** [dask/fastparquet#101]
i.e. on merge is {a,b,d} and another is {a,b,c}. Maybe a bad idea as should really be supported in upstream parquet.

**Comment by martindurant** [comment]
Sorry, I don't follow you - could you please expand?

**Comment by cottrell** [comment]
If you save parquet files in parallel, you can writer.merge them into one (some conditions apply). If you have four separate chunks, for example, there are four different merges involving only three files. Anyway, probably not that important since I don't think the merged metadata does much more than triggers a "concat" of sorts on load. But if the merge is really just metadata, then naming the merge seems like a natural abstraction.

**Comment by martindurant** [comment]
Oh, I see, you'd like
```
merge(filelist, outfile='mymetadata')
```
rather than assuming where the metadata file should go.
This could indeed be done.

On load, you can choose which row-groups to load, though, so I'm not sure it's useful to have several metadata filed containing pointers to different chunks. 

Note that dask's [dataframe.to_parquet](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_parquet) writes chunks to parquet files in parallel and creates a single metadata file for them. Perhaps this is what you want (or look at its code and tailor to your needs - it's not that complex).

**Comment by cottrell** [comment]
Exactly. I guess it does seem more natural to use the actual parquet constructs (row-groups) to slice or track subsets.
