### ISSUE TITLE
Append to existing file with different schema?

### ISSUE THREAD

**Issue by gowtham-sai** [dask/fastparquet#193]
I written a dataframe to parquet file which 256 columns. I've to append the next data to the same file but another dataframe which has less columns than original. 

Those two are different processes reading data from two different files. But both of them have few fields in common. 

Can I append the second dataframe to the file written by first dataframe ?

**Comment by martindurant** [comment]
Appending with a different schema is *not* supported. I would advise that you add the columns to your appended dataframe (even if all of the values are None/NaN). Alternatively, only read the columns of interest from the original file, and write out to a separate dataset.

Even in other parquet frameworks, it is generally only possible to add columns, not remove them, and such "evolution" is not actually part of the parquet specification.

**Comment by gowtham-sai** [comment]
Hi @martindurant 
Thanks for quick response. 

I couldn't come up with better architecture. I'm trying to solve a problem with minimal effort. 

I've a lot of **events data** flowing into Kafka and the same is written to  JSON files. We are planning to convert the json to parquet and store it in s3 and query it with presto. Ideal file size in s3 for presto to query is 500 GB. 

My json files are partitioned day/hour in local disk. I'm reading 204800 bytes at a time and writing to a parquet file in s3. I've to append the data to the same file till it reaches to 500 GB in a day, then split it to another file.
If day changes, no matter what is the existing day file size, split it to directory. So, here the problem is events schema is varies very widely. Like few of the fields might present in the previous events and might not present in the next events. 

How can I achieve ? 

1. One way is to read 500 mb of data into memory and convert it to file. But I can't really use heavy machines. 500 MB might not be big deal. But still, we want to read chunks by chunks. 

2.  If 1 is the only way to do, how much bytes of json data I need to read to make it to 500 MB of Parquet file?

Any other better ways to achieve this?

**Comment by martindurant** [comment]
Firstly, it does not seem like the data is particularly well-suited to parquet: you have key-value data rather than columnar, so forcing to columnar makes for a very sparse data-set. Are you certain that JSON is not, in fact, the best storage format? How about something more record-based like avro?

Secondly, there is an overhead associated with a) each column of the dataset, b) each row-group (chunk or partition) of the data-set. In your case, you have many of both, so I would expect performance to be bad, especially when writing to an S3 file in-place, which requires multi-part fanciness on the server. I would strongly suggest accumulating as much data as possible (on disc if not in memory) before conversion to parquet.

For your specific question, how many bytes of JSON does it take to create N bytes of parquet: the best would be to experiment a little, as it depends on a number of factors. Do not expect for the value to be consistent, especially if using compression.

**Comment by gowtham-sai** [comment]
You are correct, I've key-value data. Out of which, 15 columns are always constant and others are not constant (which varies based on event type). 

I can't go with other file formats like avro, orc or something else as porting the data to other databases such as BigQuery, Redshift, Document Db, PrestoDb (Querying) can be done easily with parquet than other file formats. 

I've size concerts because of which I can't really go with JSON formats. 2/3 of my infra cost is because of data size and network usage. So, I've to well compress and store it in s3 in a columnar file format. So that, while querying we don't query the entire while, instead will query only the columns which are required.

**Comment by martindurant** [comment]
You will probably find that, for the columns that are sparse (not the required 15), you do not save any space by converting to parquet, especially if your row-group sizes are small. This is because of the metadata required to declare each column, even if they contain no data. I am surprised that you find JSON too verbose, since it does not store keys that are not present, and your data is sparse. Also, JSON often compresses well.

If using parquet, you might do well to store the 15 required columns, but the remaining data as a single JSON- or BSON-encoded text column, i.e., dictionary-like. This will work well if the 15 columns contain the values most important to you and most frequently accessed, such as filtering criteria.

Note that fastparquet does not support writing "MAP"-type data, which would be the more portable way to write such key-value data. There are no plans to add this, since it does not match the typical tabular nature of data which plays well with parquet.

**Comment by gowtham-sai** [comment]
Well if I store json file s3, querying with presto will be painful as it has to read the entire file. I haven't done any benchmarks. But what I read from internet is, presto with parquet format, hive table for metadata is giving good performance. 

Sure, I'll check out other file formats as well. Thanks :) 👍
