### ISSUE TITLE
Support 'io.BytesIO' as a 'write' option

### ISSUE THREAD

**Issue by mime-frame** [dask/fastparquet#215]
For serverless applications, it'd be great if the write function supported a non disk option.

**Comment by mrocklin** [comment]
I think he's asking to write to something like an `io.BytesIO()`

**Comment by mime-frame** [comment]
Sorry, yes something like `io.BytesIO` 😃

**Comment by martindurant** [comment]
Sure, that should be doable now with something like this:

```python
class MemoryFiles():
    def __init__(self):
        self.output = {}

    def open(self, fn, mode='rb'):
        if mode != 'wb':
            try:
                self.output[fn].seek(0)
            except KeyError:
                raise FileNotFoundError
            return self.output[fn]
        i = io.BytesIO()
        self.output[fn] = i
        self.output[fn].close = lambda : None
        return i

In [39]: files = MemoryFiles()

In [40]: fp.write('my.parq', df, open_with=files.open)

In [41]: fp.ParquetFile('my.parq', open_with=files.open)
Out[41]: <Parquet File: {'columns': ['A'], 'rows': 9, 'name': 'my.parq', 'partitions': []}>
```

**Comment by mrocklin** [comment]
Is it reasonable to support passing a file-like directly in place of the filename?

**Comment by mrocklin** [comment]
Or I guess this doesn't make as much sense because Parquet will want to write to multiple files?

**Comment by martindurant** [comment]
In the "simple" file scheme, above, there is only one file, but in general there are many. In fact, the above would work for multiple files only if also passing `mkdirs=lambda: None` to `write`. To allow file objects would require a certain amount of reworking, because the open function is used with `with` blocks, and always tries to close the file, hence the no-op `close` method in the code. 
On the other hand, we could provide a more polished form of what's here, if it's useful to people, and as an example of using other non-filesystems.
@mrocklin , is it ever useful to Dask to be able to, for example `df.write_csv('memory://keys*.csv')`?

**Comment by mrocklin** [comment]
I doubt that this is implemented today though.  This is the first actual
user request we've gotten for this sort of thing.

**Comment by mime-frame** [comment]
BTW a quick note on our use-case: The plan is having our serverless app (Python, AWS Lambda) transform data into parquet and then send it to Firehose: http://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html

**Comment by martindurant** [comment]
I don't know anything about firehose, but would I be right to guess that it's sufficiently different from a binary-/file-store, that it makes no sense to try to wrap in a class like the ones for s3fs, hdfs3, gcsfs?

**Comment by martindurant** [comment]
@mrocklin , do you think that code based on https://github.com/dask/fastparquet/issues/215#issuecomment-331039719 is a useful as a MemoryFileSystem for dask?

**Comment by mrocklin** [comment]
Sure, that could be quite neat and it would play nicely into existing protocols.

**Comment by martindurant** [comment]
Now available in dask as "memory:" URLs
