### ISSUE TITLE
.to_parquet() returns AttributeError: 'bool' object has no attribute 'writer'

### ISSUE THREAD

**Issue by citynorman** [dask/fastparquet#229]
I'm having trouble saving to parquet files... Seems straightforward but I'm getting an exception
**code**

    import pandas as pd
    import dask.dataframe as dd
    
    ddf0 = dd.from_pandas(pd.DataFrame({'a':[5.0]*5,'b':[5]*5}),chunksize=100)
    ddf0.to_parquet('test.pq') # doesn't work
    ddf0.to_parquet('test/') # doesn't work
    ddf0.to_parquet('test.pq/files*.pq') # doesn't work

**log**

ddf0.to_parquet('test/')
Traceback (most recent call last):

  File "<ipython-input-22-69a98f435410>", line 1, in <module>
    ddf0.to_parquet('test.pq/files*.pq')

  File "/opt/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py", line 955, in to_parquet
    return to_parquet(path, self, *args, **kwargs)

  File "/opt/anaconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 439, in to_parquet
    _write_metadata(writes, filenames, fmd, path, metadata_fn, myopen, sep)

  File "/opt/anaconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 463, in _write_metadata
    fastparquet.writer.write_common_metadata(metadata_fn, fmd, open_with=myopen,

AttributeError: 'bool' object has no attribute 'writer'

**Setup**

Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

dask==0.15.0
fastparquet==0.1.2
pandas==0.20.2

Thanks for the help!

**Comment by martindurant** [comment]
Can you please ensure that you have fastparquet installed? If this is the issue, clearly, we could have done a better job in describing it.

**Comment by citynorman** [comment]
Thanks. Yes I have it installed, see the pip freeze snapshot and in any case otherwise it would give fastparquet not found error.

fastparquet==0.1.2

**Comment by citynorman** [comment]
Just case it makes a difference I am trying to save to local drive not hdfs

**Comment by apiszcz** [comment]
![image](https://user-images.githubusercontent.com/1430861/31220435-6e43d9d0-a98e-11e7-89f4-218ae3845448.png)

**Comment by apiszcz** [comment]
Another test with 5 million rows

![image](https://user-images.githubusercontent.com/1430861/31221084-8b450d86-a990-11e7-8399-2986129995fa.png)

**Comment by martindurant** [comment]
@citynorman : that you are getting serialization errors suggests you are running with the distributed scheduler, and the environment each worker sees might not be the same.

Identical same code as yours, up to and including the line `# doesn't work` - does work for me fine.
The bool the exception refers to is the variable `dask.dataframe.io.parquet.fastparquet`, which is False if the import of fastparquet failed. Since you installed using pip, can you ensure you have numba and other dependencies installed? Can you import and use fastparquet directly, like `fastparquet.write('test1.pq', df0)` (where df0 is the pandas version of the data)?

@apiszcz : the timings you should would be rather different if you repeated the load steps more than once (fastparquet jit-compiles some code on the first call).

**Comment by citynorman** [comment]
Somehow it's working now without having made any changes... You guys got the magic touch, thanks so much for your help everyone!

**Comment by martindurant** [comment]
I like a problem that solves itself :)

**Comment by apiszcz** [comment]
Update, they are much close, pyarrow ~10% slower

![image](https://user-images.githubusercontent.com/1430861/31248769-ee5b518a-a9e2-11e7-877f-096fae838e1d.png)
