### ISSUE TITLE
Should writer.encode_* functions be in encoding.py?

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#282]
It took me a while to find the parquet encoding functions, which are in the `writer.py` file.  I expected them in `encoding.py` where the decoding functions can be found. Naively, it would be nice to have both the encoding and decoding in the same file.  This would be good because it is not mixed with the pandas specific code found in `writer.py` and lets us pair up each encoder with its opposite.

Furthermore, is there a reason we can not make both the encoding and decoding functions members of <strike>`NumpyIO`</strike>`Numpy8`?  Maybe `@numba.njit` does not handle object methods well?

I have no plans to make these changes. I am only wondering if others see this too, or if there is another logical organization I may be missing, or if there are limits the optimizer imposes I am unaware.

Thank you!

**Comment by martindurant** [comment]
(I will get back to replying to your nested encoding PR shortly)

The reason for the module structure is essentially historical. In the original parquet-python, which only had reading, low-level functions like these were in a module called `encoding`. In hindsight, it should have been renamed `decoding`, and, as you suggest, some of the lower-level functions from `writer` should have been pulled out from there - that module is too monolithic. It is not entirely clear where the division between the higher and lower-level functions would be, however, so I am satisfied with the current structure, I'm not convinced that it is worth the bother to change it.

You are right that many functions work on Numba8 instances, so there is an argument that they could be methods. All I can say is that they don't *feel* very much like methods. I believe that numba should be able to JIT them just fine, although historically class support has generally lagged behind function support. For example, JIT-classes cannot be cached, whereas functions (with no JIT-class arguments) can - this is rather a shame for us, as the import time of fastparquet is consequently much slower than it could be.

Also, since there is now cython in the codebase too, it is no longer clear that using numba is warranted, the performance should be similar, but I do not have a strong motivation to change things.

**Comment by klahnakoski** [comment]
Excellent!  Thank you.  It is always nice to have my suspicion confirmed.
