### ISSUE TITLE
read parquet from byte array

### ISSUE THREAD

**Issue by virtualluke** [dask/fastparquet#329]
I am in a function receiving a byte array which happens to be a self-contained parquet object from S3 and would like to read it using fastparquet.  I am being passed the data as a byte array.  

Is there a way to do this?  I see the example using s3fs but I am in a function where the overhead of adding an s3fs call is more than I want since I already have access to the data as a byte array.  I tried reading it as fastparquet.ParquetFile(io.BytesIO(byte_array)) but get the error: "typeError: '_io.BytesIO' object is not subscriptable" (when is is checking path[0][0]=='/').

thoughts?

**Comment by martindurant** [comment]
There isn't an obvious way to do this, mainly because fastparquet expects a dataset to often be composed of *multiple* files. However, the functions you need are: 
- `ParquetFile._parse_header`, which takes an open file and sets attributes on the ParquetFile (i.e., you would have to circumvent the code in `__init__` that is currently blocking you, perhaps by creating a ParquetFile from an unrelated dataset)
- `ParquetFile.read_row_group`, see how this is called in `to_pandas()`.

**Comment by martindurant** [comment]
(that was easier than I thought)

**Comment by virtualluke** [comment]
thanks! that worked.
