### ISSUE TITLE
Would it be worth making this method accept both filepath and BytesIO/StringIO object?

### ISSUE THREAD

**Issue by aaronfowles** [dask/fastparquet#360]
When calling the `to_parquet` method in pandas, the api is not consistent when using fastparquet engine. For example, `to_csv` accepts either a filepath or a buffer. So does `to_parquet` when using the pyarrow engine. However, calling `to_parquet` when using the fastparquet engine will error when passed a buffer rather than filepath.

I think it would be good to adhere to the polymorphic api exposed by the other `to_<format>` methods and allow both filepath and buffer to be passed to `to_parquet`.

https://github.com/dask/fastparquet/blob/5b4f30a0a7fe90cc61ca5119b8a65ca614aa0a45/fastparquet/writer.py#L735

I am happy to submit a PR for this unless anyone has an objection?

**Comment by martindurant** [comment]
No objection. The wrinkle is, that parquet can in principle be written into multiple files, so the buffer version could only apply to the single-file case. The [memory file system](https://github.com/dask/dask/pull/2741) written once for Dask, but never merged, produces one or more BytesIO objects in a dictionary and may be interesting to you.

**Comment by aaronfowles** [comment]
@martindurant Thanks for the info! I'l take a look when I get a chance and see if it looks achievable.

**Comment by martindurant** [comment]
Memory file-system also experimentally offered now here: https://github.com/martindurant/filesystem_spec/blob/master/fsspec/memory.py

**Comment by aaronfowles** [comment]
Trying to get test framework running locally using pytest. I've got pytest-cython installed and running:

`py.test --doctest-cython`

I get the following error on Mac OSX High Sierra 10.13.6. I'm using PyCharm IDE but I'm also having this issue on the terminal both inside and outside virtual-env.

`________________ ERROR collecting fastparquet/test/test_api.py _________________
ImportError while importing test module '/Users/afowles/PycharmProjects/fastparquet/fastparquet/test/test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.local/share/virtualenvs/fastparquet/lib/python3.6/site-packages/_pytest/python.py:482: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../.local/share/virtualenvs/fastparquet/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
fastparquet/__init__.py:8: in <module>
    from .core import read_thrift
fastparquet/core.py:9: in <module>
    from . import encoding
fastparquet/encoding.py:11: in <module>
    from .speedups import unpack_byte_array
E   ModuleNotFoundError: No module named 'fastparquet.speedups'`

I also noticed the following when running `python setup.py install` and thought the reference to plain-text __file__ was odd:

`fastparquet.__pycache__.speedups.cpython-36: module references __file__
fastparquet.test.__pycache__.test_with_n.cpython-36: module references __file__
`

Any thoughts?

**Comment by martindurant** [comment]
You should not need `--doctest-cython`, but install the source as you normally would do, e.g.,
```
pip install -e .
```
(run from the source directory).

**Comment by ubdussamad** [comment]
Hi, i am trying to install fastparquet in linux envir, the install wroks fine (i guess):
`running install
running bdist_egg
running egg_info
writing fastparquet.egg-info/PKG-INFO
writing top-level names to fastparquet.egg-info/top_level.txt
writing dependency_links to fastparquet.egg-info/dependency_links.txt
writing requirements to fastparquet.egg-info/requires.txt
reading manifest file 'fastparquet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fastparquet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/parquet.thrift -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/thrift_structures.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/api.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/__init__.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/speedups.c -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/compression.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/speedups.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/writer.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/schema.py -> build/bdist.linux-x86_64/egg/fastparquet
creating build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_converted_types.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_util.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/__init__.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_aroundtrips.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_thrift_structures.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_encoding.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_speedups.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_partition_filters_specialstrings.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/util.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_read.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_with_n.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_compression.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_api.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_dataframe.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/test/test_output.py -> build/bdist.linux-x86_64/egg/fastparquet/test
copying build/lib.linux-x86_64-3.5/fastparquet/encoding.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/converted_types.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/util.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/core.py -> build/bdist.linux-x86_64/egg/fastparquet
copying build/lib.linux-x86_64-3.5/fastparquet/speedups.pyx -> build/bdist.linux-x86_64/egg/fastparquet
creating build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift
copying build/lib.linux-x86_64-3.5/fastparquet/parquet_thrift/__init__.py -> build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift
creating build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet
copying build/lib.linux-x86_64-3.5/fastparquet/parquet_thrift/parquet/__init__.py -> build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet
copying build/lib.linux-x86_64-3.5/fastparquet/parquet_thrift/parquet/constants.py -> build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet
copying build/lib.linux-x86_64-3.5/fastparquet/parquet_thrift/parquet/ttypes.py -> build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet
creating build/bdist.linux-x86_64/egg/fastparquet/benchmarks
copying build/lib.linux-x86_64-3.5/fastparquet/benchmarks/columns.py -> build/bdist.linux-x86_64/egg/fastparquet/benchmarks
copying build/lib.linux-x86_64-3.5/fastparquet/dataframe.py -> build/bdist.linux-x86_64/egg/fastparquet
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/thrift_structures.py to thrift_structures.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/api.py to api.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/compression.py to compression.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/writer.py to writer.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/schema.py to schema.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_converted_types.py to test_converted_types.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_util.py to test_util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_aroundtrips.py to test_aroundtrips.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_thrift_structures.py to test_thrift_structures.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_encoding.py to test_encoding.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_speedups.py to test_speedups.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_partition_filters_specialstrings.py to test_partition_filters_specialstrings.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_read.py to test_read.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_with_n.py to test_with_n.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_compression.py to test_compression.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_api.py to test_api.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_dataframe.py to test_dataframe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/test/test_output.py to test_output.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/encoding.py to encoding.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/converted_types.py to converted_types.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/core.py to core.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet/constants.py to constants.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/parquet_thrift/parquet/ttypes.py to ttypes.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/benchmarks/columns.py to columns.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/dataframe.py to dataframe.cpython-35.pyc
creating stub loader for fastparquet/speedups.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/fastparquet/speedups.py to speedups.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying fastparquet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fastparquet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fastparquet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fastparquet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fastparquet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/fastparquet-0.2.1-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fastparquet-0.2.1-py3.5-linux-x86_64.egg
removing '/usr/local/lib/python3.5/dist-packages/fastparquet-0.2.1-py3.5-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.5/dist-packages/fastparquet-0.2.1-py3.5-linux-x86_64.egg
Extracting fastparquet-0.2.1-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
fastparquet 0.2.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/fastparquet-0.2.1-py3.5-linux-x86_64.egg
Processing dependencies for fastparquet==0.2.1
Searching for pytest-runner==5.1
Best match: pytest-runner 5.1
Processing pytest_runner-5.1-py3.5.egg
pytest-runner 5.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/pytest_runner-5.1-py3.5.egg
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /home/samad/.local/lib/python3.5/site-packages
Searching for thrift==0.11.0
Best match: thrift 0.11.0
Processing thrift-0.11.0-py3.5-linux-x86_64.egg
thrift 0.11.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/thrift-0.11.0-py3.5-linux-x86_64.egg
Searching for numpy==1.14.0
Best match: numpy 1.14.0
Adding numpy 1.14.0 to easy-install.pth file

Using /home/samad/.local/lib/python3.5/site-packages
Searching for numba==0.45.1
Best match: numba 0.45.1
Processing numba-0.45.1-py3.5-linux-x86_64.egg
numba 0.45.1 is already the active version in easy-install.pth
Installing pycc script to /usr/local/bin
Installing numba script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages/numba-0.45.1-py3.5-linux-x86_64.egg
Searching for pandas==0.24.2
Best match: pandas 0.24.2
Adding pandas 0.24.2 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for llvmlite==0.29.0
Best match: llvmlite 0.29.0
Processing llvmlite-0.29.0-py3.5-linux-x86_64.egg
llvmlite 0.29.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/llvmlite-0.29.0-py3.5-linux-x86_64.egg
Searching for python-dateutil==2.7.5
Best match: python-dateutil 2.7.5
Adding python-dateutil 2.7.5 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for pytz==2018.7
Best match: pytz 2018.7
Adding pytz 2018.7 to easy-install.pth file

Using /home/samad/.local/lib/python3.5/site-packages
Finished processing dependencies for fastparquet==0.2.1`

Above is the install output.

But while running the tests, one of them fails ( fastparquet.speedups not found):

`============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/samad/parquet/fastparquet, inifile: setup.cfg
collecting ... 
==================================== ERRORS ====================================
________________ ERROR collecting fastparquet/test/test_api.py _________________
ImportError while importing test module '/home/samad/parquet/fastparquet/fastparquet/test/test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/dist-packages/_pytest/python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
fastparquet/__init__.py:8: in <module>
    from .core import read_thrift
fastparquet/core.py:9: in <module>
    from . import encoding
fastparquet/encoding.py:11: in <module>
    from .speedups import unpack_byte_array
E   ModuleNotFoundError: No module named 'fastparquet.speedups'
=============================== warnings summary ===============================
/usr/lib/python3/dist-packages/pytz/lazy.py:5
  /usr/lib/python3/dist-packages/pytz/lazy.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping as DictMixin

/usr/lib/python3/dist-packages/matplotlib/__init__.py:376
  /usr/lib/python3/dist-packages/matplotlib/__init__.py:376: DeprecationWarning: invalid escape sequence \.
    pattern = '3\.1\d+'

/usr/lib/python3/dist-packages/matplotlib/cbook.py:559
  /usr/lib/python3/dist-packages/matplotlib/cbook.py:559: DeprecationWarning: invalid escape sequence \*
    """

/usr/lib/python3/dist-packages/matplotlib/cbook.py:1129
  /usr/lib/python3/dist-packages/matplotlib/cbook.py:1129: DeprecationWarning: invalid escape sequence \S
    _find_dedent_regex = re.compile("(?:(?:\n\r?)|^)( *)\S")

/usr/lib/python3/dist-packages/matplotlib/cbook.py:1947
  /usr/lib/python3/dist-packages/matplotlib/cbook.py:1947: DeprecationWarning: invalid escape sequence \m
    '''

/usr/lib/python3/dist-packages/matplotlib/rcsetup.py:900
  /usr/lib/python3/dist-packages/matplotlib/rcsetup.py:900: DeprecationWarning: invalid escape sequence \-
    'mathtext.sf':             ['sans\-serif', validate_font_properties],

/usr/lib/python3/dist-packages/pyparsing.py:1963
  /usr/lib/python3/dist-packages/pyparsing.py:1963: DeprecationWarning: invalid escape sequence \g
    ret = re.sub(self.escCharReplacePattern,"\g<1>",ret)

/usr/lib/python3/dist-packages/pyparsing.py:699
  /usr/lib/python3/dist-packages/pyparsing.py:699: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    collections.MutableMapping.register(ParseResults)

/usr/lib/python3/dist-packages/pyparsing.py:2241
  /usr/lib/python3/dist-packages/pyparsing.py:2241: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    elif isinstance( exprs, collections.Sequence ):

/usr/lib/python3/dist-packages/matplotlib/colors.py:228
  /usr/lib/python3/dist-packages/matplotlib/colors.py:228: DeprecationWarning: invalid escape sequence \A
    hexColorPattern = re.compile("\A#[a-fA-F0-9]{6}\Z")

/usr/lib/python3/dist-packages/matplotlib/ticker.py:619
/usr/lib/python3/dist-packages/matplotlib/ticker.py:619
  /usr/lib/python3/dist-packages/matplotlib/ticker.py:619: DeprecationWarning: invalid escape sequence \m
    self.format = '$\mathdefault{%s}$' % self.format

/usr/lib/python3/dist-packages/matplotlib/ticker.py:796
/usr/lib/python3/dist-packages/matplotlib/ticker.py:796
  /usr/lib/python3/dist-packages/matplotlib/ticker.py:796: DeprecationWarning: invalid escape sequence \m
    return '$\mathdefault{0}$'

/usr/lib/python3/dist-packages/matplotlib/ticker.py:816
/usr/lib/python3/dist-packages/matplotlib/ticker.py:816
  /usr/lib/python3/dist-packages/matplotlib/ticker.py:816: DeprecationWarning: invalid escape sequence \m
    return ('$\mathdefault{%s%s^{%.2f}}$') % \

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================== 16 warnings, 1 error in 1.33 seconds =====================`

What am i missing here?

**Comment by martindurant** [comment]
This does not look related to the issue title - I suppose it should be a new issue. Having said that, I don't immediately see what's going on, as I usually rely on conda for binary installation.

**Comment by ubdussamad** [comment]
@martindurant Let me check, i have a clue to what maybe wrong, though I'll learn conda and try to install it fresh through that, but if that still dosent works I'll raise an issue.
