### ISSUE TITLE
Support pathlib Path inputs

### ISSUE THREAD

**Issue by kylebarron** [dask/fastparquet#365]
Currently when I do
```py
import fastparquet as fp
from pathlib import Path
fp.ParquetFile(Path('/path/to/file.parquet'))
```
I get a `TypeError`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-56-691671112f6c> in <module>()
----> 1 pf = fp.ParquetFile((self.data_dir / 'raw' / 'pos' / f'pos{self.year}.parquet'))

~/disk/age-discontinuities/local/miniconda/envs/age-discont/lib/python3.6/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
     90         else:
     91             try:
---> 92                 fn2 = join_path(fn, '_metadata')
     93                 self.fn = fn2
     94                 with open_with(fn2, 'rb') as f:

~/disk/age-discontinuities/local/miniconda/envs/age-discont/lib/python3.6/site-packages/fastparquet/util.py in join_path(*path)
    305     abs_prefix = ''
    306     if path and path[0]:
--> 307         if path[0][0] == '/':
    308             abs_prefix = '/'
    309             path = list(path)

TypeError: 'PosixPath' object does not support indexing
```

Are there any plans to support pathlib inputs?

**Comment by martindurant** [comment]
No such plans, unless you wish to add it. It would amount to unwrapping the `Path` on the first line of the init method.

**Comment by davetapley** [comment]
Something must have changed (using `fsspec`?) since this was first opened, because this now works:
```py
fp.ParquetFile(Path('/path/to/file.parquet'))
```

... as long as the file exists.

If it doesn't you get: `TypeError: argument of type 'PosixPath' is not iterable` as this tries to `in`:
https://github.com/dask/fastparquet/blob/f747fe606e3b7c0c8c23f07d169296c862d69a54/fastparquet/api.py#L148

Would be nice to get a `FileNotFound` to be consistent with:
https://github.com/dask/fastparquet/blob/f747fe606e3b7c0c8c23f07d169296c862d69a54/fastparquet/api.py#L178

I don't see anything like `filename` in [`AbstractFileSystem`](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=isdir#fsspec.spec.AbstractFileSystem), I guess that would be 'correct' way to do it? 🤔

**Comment by davetapley** [comment]
@martindurant want a PR?

**Comment by martindurant** [comment]
That would be fine
