### ISSUE TITLE
ARRAY<string> data type with fastparquet?

### ISSUE THREAD

**Issue by alexwbai** [dask/fastparquet#372]
Hey quick question for you smart people-

I have an AWS pipeline that outputs data to S3 in parquet format.  I've defined some DDL (using AWS Athena) which maps a column in the parquet data as an ARRAY<string> datatype.  The data for this column looks like this: [string,string,string].  This part works fine.

I need to manually add some additional parquet data to this S3 bucket outside of the pipeline.  I have decided to use fastparquet to do it and I seem to be running into an issue where after saving the parquet file with fastparquet my column of [string,string,string] is not being read as ARRAY<string>.  If I change the DDL to just STRING it works.

Is there any trick to convert a column with data like this ['string1','string2','string3'] to be able to be discovered as an ARRAY<STRING> datatype when saved with fastparquet?  Or is this more of a pandas issue?  Thanks for any help!

**Comment by martindurant** [comment]
I'm afraid fastparquet does not write ARRAY or any other nested data type. Implementing limited nested reading was already quite a stretch, since it doesn't fit the pandas data model well at all. Your only option may be indeed to convert to string, or use JSON encoding (which your AWS reader may or may not support, I don't know).

**Comment by alexwbai** [comment]
Hi Martin,

Really appreciate the quick response.  Thanks for letting me know!

AlexW
