### ISSUE TITLE
Discussion: GSOC?

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#397]
I am looking to mentor some work on fastparquet. I intend for the coding to proceed on a fork, but I am wondering how much (or how little) you (the project owner) would like to be involved:

* You can be hands off (default) - we will work off a fork, and submit a series of PRs near the end of the summer.
* You can provide reviews (1 or 2 hours per week) - we can work on a fastparquet branch, and you get to direct the work in progress.
* You can help mentor (4hours per week) - and guide the student on a near-daily basis.

In all cases, I will give you updates on the project, I will be around to guide the student, and ensure the administrative stuff is done. **IF** this happens, then the student will be working, full time from about May to end of August.

The project has been added here: https://wiki.mozilla.org/Community:SummerOfCode19:Brainstorming#2019_Proposed_Project_List

**Comment by martindurant** [comment]
I am certainly available for advice and code reviews, and would be happy to see more features or speed improvements in fastparquet. The most obvious would be along the lines of the discussion with Jim P about structured data.

However, I feel I should point out that fastparquet is not really being heavily developed any more, since it meets most users' needs, and arrow's parquet provides a sufficiently good alternative. My main work is now on [Intake](https://intake.readthedocs.io/en/latest/).
