### ISSUE TITLE
Converting CSV to Parquet. RuntimeError: Compression 'snappy' not available

### ISSUE THREAD

**Issue by hmajumdar** [dask/fastparquet#402]
I am using Python 3.6 interpreter in my PyCharm venv, and trying to convert a CSV to Parquet.

```
import pandas as pd    
df = pd.read_csv('/parquet/drivers.csv')
df.to_parquet('output.parquet', engine='fastparquet')
```

I get this **error**

`/Users/python parquet/venv/lib/python3.6/site-packages/fastparquet/compression.py", line 131, in compress_data (algorithm, sorted(compressions))) RuntimeError: Compression 'snappy' not available. Options: ['GZIP', 'UNCOMPRESSED']`

I Installed **python-snappy 0.5.3** but still getting the same error? Do I need to install any other library? If I use **PyArrow 0.12.0** engine instead, I don't see this error

**Comment by martindurant** [comment]
What happens when you do `import snappy`?
How did you install snappy? If with pip, you will need the non-python libraries too, often as system packages; conda does this automatically.
Note that it was not my choice that snappy should be the default here -  you could choose to save uncompressed, which may be faster.

**Comment by seshness** [comment]
I ran into this error, and then an even more confusing
```
AttributeError: 'module' object has no attribute 'compress'
```

I had accidentally installed [snappy==2.6.1](https://pypi.org/project/snappy/), instead of installing [python-snappy==0.5.4](https://pypi.org/project/python-snappy/).

On macOS I installed python-snappy by running
```
$ brew install snappy # snappy library from Google
$ CPPFLAGS="-I/usr/local/include -L/usr/local/lib" pip install python-snappy
```
sourcing these instructions from https://github.com/andrix/python-snappy#frequently-asked-questions.

I realize this doesn't quite answer the initial question, but if anyone else lands here from Google, I hope this helps.

**Comment by Dunni3** [comment]
I encountered this error when fastparquet was installed during conda environment creation. It appears that conda installed [snappy](https://pypi.org/project/snappy/) (an irrelevant package) but did not install [python-snappy](https://pypi.org/project/python-snappy/) (the package actually needed to use fastparquet).

I do not know whether conda was responsible for installing the wrong "snappy" or if it is a fastparquet issue.

**Comment by martindurant** [comment]
fastparquet does not not declare snappy as a dependency at all ( https://github.com/conda-forge/fastparquet-feedstock/blob/master/recipe/meta.yaml for conda-forge and https://github.com/dask/fastparquet/blob/master/requirements.txt for pip). Is this the anaconda defaults channel that you are talking about? If so, you should raise an issue with them.
