### ISSUE TITLE
"Non-categorical multi-index is likely brittle"

### ISSUE THREAD

**Issue by Dr-Irv** [dask/fastparquet#434]
We are switching from HDF files to Parquet files, and got this warning:
"Non-categorical multi-index is likely brittle"

Now we are wondering if we shouldn't have switched.  I'm thinking this warning was from the time before fastparquet had support for `MultiIndex` column names.

Can anyone indicate what may still be brittle?

**Comment by martindurant** [comment]
Brittle here implies that the implementation depends on pandas internal data organisation, which could change from one release to the next. A multi-index is represented as a category-like set of columns, but not exactly the same. There may well be corner cases that are not tested for. You can, though, always choose to load the columns as they are, and then set the index afterwards; this comes with a performance penalty, but is perhaps safer. You should usually store multi-index data as categorical in any case, since it will likely be more efficient, in disc space, memory and load time.

**Comment by Dr-Irv** [comment]
Thanks!

**Comment by Dr-Irv** [comment]
Is it the case that if we do `df.to_parquet('foo.parq')` in one script, and `df=pd.read_parquet('foo.parq')` in another script, when the `MultiIndex` was not categorical, that we could still see the brittle behavior, assuming we don't change pandas versions?

**Comment by martindurant** [comment]
I expect it to work, but it may break upon a new version of pandas in the future. When that happens, if people are still using this library, I'll try to fix it.

**Comment by Dr-Irv** [comment]
Thanks again!
