### ISSUE TITLE
Partitioning on multiple columns where one is a categorical-datetime

### ISSUE THREAD

**Issue by alexifm** [dask/fastparquet#440]
Hey, this is actually a bug in Pandas that I just reported and created a PR for.
https://github.com/pandas-dev/pandas/issues/26859

It's an issue for fastparquet here:
https://github.com/dask/fastparquet/blob/6c20042649bb98f4aa6a4aa4589ccd693cd2aee4/fastparquet/writer.py#L939

**Comment by martindurant** [comment]
Please let me know @alexifm when your fix is merged, and what should be done here about it

**Comment by haleemur** [comment]
@martindurant @alexifm, I believe we can close this issue since `zip(sorted(gb.indices), sorted(gb))` has been replaced with `sorted(gb)`, so we don't encounter cases where `sorted(gb.indices)` & `sorted(gb)` have different lengths.

This change happened in this [PR 525](https://github.com/dask/fastparquet/issues/525#issuecomment-725220498_)
