### ISSUE TITLE
dataframe data write to .parq fall with error:Column name must be a string. Got column 0 of type int

### ISSUE THREAD

**Issue by jiahairui** [dask/fastparquet#519]
**What happened**:
when write DataFrame to file data.parq,  throw TypeError:Column name must be a string. Got column 0 of type int.
if I use following code, it can work correctly.
df = pd.DataFrame(np.random.randint(1000,size=(4, 4)), columns=list('ABCD'))

when I use following code, it fall with error.
df = pd.DataFrame(np.random.randint(1000,size=(4, 4)))

**What you expected to happen**:
write to .parq file correctly even if not exist columns list. 

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import numpy as np
import pandas as pd
from fastparquet import write

df = pd.DataFrame(np.random.randint(1000,size=(4, 4)))
write("data.parq", df)
```

**Anything else we need to know?**:

**Environment**:
- fastparquet version: 1.0.0
- Dask version:-
- Python version: 3.6.9
- Operating System:Ubuntu 18.04.1 LTS
- Install method (conda, pip, source):pip

**Comment by martindurant** [comment]
I wouldn't consider this a bug, since the error message is quite clear: fastparquet only supports columns with string labels, because this is what parquet assumes (without some automatic coercion of data types). You could propose an enhancement to gain this feature, but it would need careful justification and description of exactly what the process would be. I think its probably far simpler to leave the onus on the caller to decide for themselves how to provide string column labels.

**Comment by jiahairui** [comment]
I see, thank you. 
Because when I use following code, it print the column labels like '0,1,2,3', so I think it maybe can as labels default in parquet file.
df = pd.DataFrame(np.random.randint(1000,size=(4, 4)))
print(df)
df.to_csv("data.csv", index = False)
Now, I create string with number clearly，and provide it to caller.
