### ISSUE TITLE
Hive partitions coerced to unwanted type

### ISSUE THREAD

**Issue by postelrich** [dask/fastparquet#528]
`val_to_num` gets called when parsing hive paths to categoricals here: https://github.com/dask/fastparquet/blob/0402257560e20b961a517ee6d770e0995e944163/fastparquet/api.py#L596 I just want the column to be returned as a string type. There doesn't appear a way to override this behavior. 

**Example**
```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'date': ['2020-10-01']*5 + ['2020-10-02']*5,
                   'foo': list(range(10))})
ddf = dd.from_pandas(df, npartitions=1)
ppath = 'dask_test.parquet'
ddf.to_parquet(ppath, partition_on=['date'])
df2 = dd.read_parquet(ppath).compute() #.to_dict('records')
df2.date.cat.categories[0]
# Timestamp('2020-10-01 00:00:00')
```

An override argument could be offered or maybe the parquet metadata could store the dtype.

**Comment by haleemur** [comment]
This is an issue, and it is one of the challenges that fastparquet will write a file, but read it in slightly differently. Some changes are less meaningful than others. However, I would consider incorrect types to be one of the bigger challenges in using fastparquet.

Metadata is not stored regarding partitioned columns, and the partitioned columns are inferred using directory structure. We could attempt to resolve this by
 
* storing column-metadata for each partition
* reading & applying the metadata when `ParquetFile.to_pandas` or `dd.read_parquet` are called.

Partitioning is such a core feature of the parquet format, that I believe it would be important to ensure that the way this metadata is stored & read are the same between pyarrow & fastparquet. Otherwise users will suffer from inconsistent behaviour if they need to use both libraries.

**Comment by haleemur** [comment]
Another thing to consider is whether to keep the column as categorical when read in. I believe all partitions get converted to categorical upon reading currently, and I am hesitant about changes to that behaviour because it might break existing code

**Comment by martindurant** [comment]
I totally agree with the approach, metadata for the partitioning columns should appear in the "pandas metadata" part of the global _metadata file, so that correct types can be applied on load. Whether or not that's categorical will not be critical for many applications, but seems like a good idea for str.

**Comment by postelrich** [comment]
Yup metadata would be the way I would do it. Another thing I would gripe on in the same context, but could be a separate issue, is somehow storing the sort order for the partition.

**Comment by postelrich** [comment]
@martindurant @haleemur I made PR to fix this. Let me know your thoughts. https://github.com/dask/fastparquet/pull/530
