### ISSUE TITLE
What is 'distinct_count' in 'statistics'?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#589]
Hi,

Please, what is `distinct_count` in dict returned by `statistics`?
I see it is 'always' set to None.
(I made quickly a seach in fastparquet Github on keyword `distinct_count`, and the few tickets that have been returned contain example of this).

For instance, in ticket #560 (one from me actually :)), the code snippet and returned result illustrate this:
```python
from os import path as os_path
import pandas as pd
import fastparquet as fp
file_path = os_path.expanduser('~/Documents/code/data/test_data')
df=pd.DataFrame({'a':[1,2,3], 'b':['aha', 'oho', 'aha']})
df['b']=df['b'].astype('category')
fp.write(file_path, df, partition_on=['b'], file_scheme='hive')

# Check statistics
print(fp.ParquetFile(file_path).statistics)
```

Returned results:
 ```python
{'min': {'a': [1, 2]},
 'max': {'a': [3, 2]},
 'null_count': {'a': [0, 0]},
 'distinct_count': {'a': [None, None]}}
```

I would have thought that it could be counting distinct values (something like `len(df['a'].unique())`).

Thanks in advance for your feedback.
Bests,

**Comment by martindurant** [comment]
This comment answers both this and #590

The canonical definition of metadata types for parquet can be found at https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift

A similar, but older, copy of this exists in the fastparquet repo, and is compiled in into the set of classes in the `ttypes` module, which is what you see when you investigate any of the thrift objects attached to a `fastparquet.ParquetFile`. The definitions include features that parquet theoretically supports but in practice are not implemented consistently (or anywhere) across the various parquet readers and writers. 

For example, a column contains a `distinct_count`, which is optional; it does mean exactly what you think it does. Fastparquet does not populate this value when writing, since that would take extra time, and there is nothing particular to be gained from its existence on read, except to report it to the user. I would be surprised if any parquet framework makes use of it. Similarly, a pandas data frame might happen to have values in some column sorted, but this is not the same as asserting that the column has a natural function as one of `sorting_columns` - and what would the reader do with this information? I *might* be useful if we implemented row-wise filtering (once we meet a condition, all further rows are good), but we don't.

**Comment by yohplala** [comment]
Thanks a lot Martin, crystal clear! Closing ticket.

**Comment by tcrasset** [comment]
I have a use for `distinct_count`.
I am using parquet to store large datasets of multiple GBs.
As such, I want to gather the most information on the dataset without streaming the whole file over the network, and without loading the whole file into memory.

One required step in our pipeline is to do one-hot encoding, which consists in creating an additional column for every unique value in the dataset.
After that, the data needs to be loaded into memory for it's final task.
Since one-hot-encoding increases the memory drastically, as a cost optimization, when we have to load it into memory, we want to spawn a Kubernetes pod with the right amount of memory allocated, not more.

Knowing the `distinct_count` would allow me to know the memory constraint, as I could compute how many columns the dataset would have after one-hot encoding.
