### ISSUE TITLE
Broken compat between fastparquet(0.7.0) and pyarrow

### ISSUE THREAD

**Issue by lithomas1** [dask/fastparquet#650]
**What happened**:
DF with datetime64 doesn't round-trip correctly with fastparquet writing df and pyarrow reading it.
(dtypes are different)
**What you expected to happen**:
It to roundtrip correctly.
**Minimal Complete Verifiable Example**:

```python
import pandas as pd
s = pd.DataFrame({"a":pd.date_range("20130101", periods=3)})
s.dtypes
# datetime64[ns]
s.to_parquet("test.parquet", engine="fastparquet")
pd.read_parquet("test.parquet", engine="pyarrow").dtypes
# datetime64[ns, UTC]
```

**Anything else we need to know?**:

**Environment**:

- Python version: 3.8.8
- Operating System: Windows
- Install method (conda, pip, source): pip
- pyarrow: 4.0.1
- pandas: 1.4.0dev(reproduces on 1.3 I think)
- fastparquet: 0.7.0

**Comment by martindurant** [comment]
This is a pyarrow bug - it produces an object column with timestamp contents. So it seems it's reading the data correctly but not producing the right series.

**Comment by jorisvandenbossche** [comment]
I think this is rather a fastparquet bug (or at least caused by different behaviour in fastparquet). 

Using the example from above, but writing the DataFrame with both latest fastparquet and pyarrow:

```
In [6]: s.to_parquet("test_fastparquet.parquet", engine="fastparquet")

In [7]: s.to_parquet("test_pyarrow.parquet", engine="pyarrow")

In [8]: import pyarrow.parquet as pq

In [9]: pq.read_metadata("test_fastparquet.parquet").schema
Out[9]: 
<pyarrow._parquet.ParquetSchema object at 0x7f06b089c900>
required group field_id=-1 schema {
  optional int64 field_id=-1 a (Timestamp(isAdjustedToUTC=true, timeUnit=nanoseconds, is_from_converted_type=false, force_set_converted_type=false));
}

In [10]: pq.read_metadata("test_pyarrow.parquet").schema
Out[10]: 
<pyarrow._parquet.ParquetSchema object at 0x7f06b08d9400>
required group field_id=-1 schema {
  optional int64 field_id=-1 a (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
}
```

You can see that fastparquet sets the `isAdjustedToUTC` flag to true, while pyarrow sets it to false (because the original pandas datetime column has no timezone). 
And when reading, if pyarrow sees a column with `isAdjustedToUTC=true`, it will make this a timezone-aware column.

**Comment by martindurant** [comment]
Whilst the [doc](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp) is less than clear, it definitely states that the former timestamp behaviour is equivalent to `isAdjustedToUTC=True` under "Backward compatibility".

**Comment by jorisvandenbossche** [comment]
The "Backward compatibility" table shows (*I think*) what is expected when *reading* data with only old ConvertedType annotations (so how to interpret eg TIMESTAMP_MILLIS in terms of a new LogicalType). 
When it comes to *writing* data, it's the "Forward compatibility" table that applies, and the text suggest to always annotate the data with an old ConvertedType as well even when using the new LogicalType (and the table shows which to use). 

The new LogicalType has more features (stores more information) compared to the ConvertedType, so there is no exact 1:1 mapping between both in case of local timestamp semantics. That is unavoidable. But if you read the "Local semantics (timestamps not normalized to UTC)" section of those parquet docs, I think that describes quite precisely the timezone-naive behaviour of pandas.

Because of those inherent issues, pyarrow has some extra logic to deal with this when reading data with only the ConvertedType annotation (which in itself doesn't distinguish between utc-adjusted vs local semantics). For example, when writing the above example with fastparquet 0.6.3, I get:

```
In [4]: pq.read_metadata("test_fastparquet_063.parquet").schema
Out[4]: 
<pyarrow._parquet.ParquetSchema object at 0x7f215191e080>
required group field_id=-1 schema {
  optional int64 field_id=-1 a (Timestamp(isAdjustedToUTC=true, timeUnit=microseconds, is_from_converted_type=true, force_set_converted_type=false));
}

In [5]: pd.read_parquet("test_fastparquet_063.parquet", engine="pyarrow").dtypes
Out[5]: 
a    datetime64[ns]
dtype: object
```

So you can see now that we do read the parquet schema as `isAdjustedToUTC=true`, but the resulting pandas table nonetheless has a timezone-naive datetime64 column (to preserve old behaviour where pyarrow "incorrectly" interpreted TIMESTAMP_MICROS as local (timezone-naive) timestamps; fastparquet has the same behaviour here as pyarrow). This is tracked via the extra `is_from_converted_type` information in the pyarrow LogicalType implementation.

**Comment by martindurant** [comment]
Fine, I'll fix it. I still think it's the parquet documentation that's at fault...
