### ISSUE TITLE
Support for pandas Float64 (capitalized)?

### ISSUE THREAD

**Issue by ilCatania** [dask/fastparquet#685]
Hi, is there any plan to add support for pandas `Float64` (capitalized)?
I've been using it in place of `float64` to identify nullable columns (as per [this stackoverflow answer](https://stackoverflow.com/a/65580589/902755) even though probably the internal implementation is the same...) and I'm getting an error when writing to parquet.

My dependencies:
```
pandas==1.2.5
fastparquet==0.7.1
```
Repro code:
```python
import pandas as pd
df = pd.DataFrame({"s": ["a", "b", "c"], "v": [1,2,3]})
df = df.astype({"s": "string", "v": "Float64"})
df.to_parquet("/tmp/test.parq", engine="fastparquet")
```
which raises:
```
  File "/export/data/gcatania/projects/monorepo/venv/lib/python3.7/site-packages/fastparquet/writer.py", line 749, in make_metadata
    object_encoding=oencoding, times=times)
  File "/export/data/gcatania/projects/monorepo/venv/lib/python3.7/site-packages/fastparquet/writer.py", line 218, in find_type
    raise ValueError("Don't know how to convert data type: %s" % dtype)
ValueError: Don't know how to convert data type: Float64
```
but works with `engine="pyarrow"`.

**Comment by martindurant** [comment]
I can't find a reference or when Float64 was introduced. It would be easy to add support for writing, although it would take more work to read back exactly the same Float type.
It raises the question of what happens when you have both NULLs and NaNs. Maybe in the easiest case, a round-trip would convert both to NaN and return a standard float type.
