### ISSUE TITLE
question: direct read/write with numpy recarrays?

### ISSUE THREAD

**Issue by beckermr** [dask/fastparquet#746]
How much work do you all estimate it would be to implement a direct read/writes with numpy recarrays?

I know that categoricals and missing data would be fun edge cases here. :)

**Comment by yohplala** [comment]
Hi @beckermr ,
I am sorry, I have no experience about numpy [recarrays](https://numpy.org/doc/stable/reference/generated/numpy.recarray.html).
It seems to be easily mappable to pandas dataframes.
What would be the point of integrating support for this array format over making a conversion from it to pandas dataframe, then giving this pandas dataframes to fastparquet?

For your information, I have coded [oups](https://github.com/yohplala/oups) which is based on fastparquet to write/read parquet files.
oups accepts vaex dataframes.
Similarly to what I mentionned above, instead of trying to force vaex dataframe support into fastparquet, I managed a vaex to pandas dataframes in a layer above fastparquet (i.e. in oups).

I have no experience about numpy recarrays as said.
My understanding of pandas dataframes is that roughly a pandas dataframe is a numpy arrays with metadata.
It seems to me that metadata are a bit used everywhere in fastparquet. It means you would neeed to tweak fastparquet "a bit everywhere".

Does it worth it?
What is your motivation, gaining speed?
 
Thanks for your feedback, bests.

**Comment by martindurant** [comment]
Agreed, it is probably easier to go via pandas than anything else.
If you look at the code, the actual column writers do work on single numpy arrays, which you can readily extract from your rec-array, so you could hook something up if you wanted.

**Comment by beckermr** [comment]
Right. I was trying to avoid excessive memory consumption by reading directly into a reference on the recarray. That may not be possible or easy though.

**Comment by martindurant** [comment]
Unfortunately, pandas use massively outweighs rec-arrays :)

**Comment by beckermr** [comment]
It could also be into a structured numpy dtype but I don't actually know the memory layout of structured dtypes.

**Comment by martindurant** [comment]
I believe a structured dtype is identical in storage to a rec-array, more or less just a more recent description of the same thing.

**Comment by beckermr** [comment]
Ok. I'll see what's possible but seems like a big lift.

**Comment by yohplala** [comment]
> Right. I was trying to avoid excessive memory consumption by reading directly into a reference on the recarray.

What I was hinting is that as base data format of pandas dataframe is numpy array (as fare as I understand), creating a pandas dataframe from a numpy array should not take any memory, or only very little. (it is a guess from me, but this seems natural)

**Comment by martindurant** [comment]
> creating a pandas dataframe from a numpy array should not take any memory

This should, of course, be tested and I am not sure it is true - I think pandas may choose to split and rejoin the constituent numpy arrays, causing memory duplication.

**Comment by beckermr** [comment]
I think there are likely factors of 2x floating around here plus the time overhead of copies. Thanks for the info everyone. I'll check this out and report back as time allows.
